name: overscripted
channels:
    - defaults
    - conda-forge
dependencies:
    - dask=1.1.4
    - distributed=1.26.0
    - findspark=1.3.0
    - jupyter=1.0.0
    - python=3.6
    - pyarrow=0.12.1
    - pandas=0.24.2
    - tldextract=2.2.0
